# Generated by Django 5.2.8 on 2025-11-28 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название мероприятия')),
                ('date', models.DateTimeField(verbose_name='Дата проведения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(blank=True, default=None, null=True, verbose_name='Активно?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ('date',),
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='users', to='datacenter.role', verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(verbose_name='Имя выступающего')),
                ('title', models.CharField(verbose_name='Название доклада')),
                ('description', models.TextField(verbose_name='Описание')),
                ('queue', models.PositiveIntegerField(verbose_name='Порядок в расписании')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало выступления')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало выступления')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.event', verbose_name='Мероприятие')),
                ('speaker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.user', verbose_name='ID выступающего')),
            ],
            options={
                'verbose_name': 'Доклад',
                'verbose_name_plural': 'Доклады',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда был задан вопрос')),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='datacenter.talk', verbose_name='Вопрос к')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('created_at',),
            },
        ),
    ]
