# Generated by Django 5.2.8 on 2025-12-01 01:16

from django.db import migrations


def add_roles(apps, schema_editor):
    Role = apps.get_model('datacenter', 'Role')
    Role.objects.create(title="Пользователь")
    Role.objects.create(title="Докладчик")
    Role.objects.create(title="Администратор")


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0002_event_alter_user_nickname_alter_user_role_talk_and_more'),
    ]

    operations = [
        migrations.RunPython(add_roles)
    ]
