# Generated by Django 5.2.8 on 2025-12-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0003_auto_20251201_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.BooleanField(default=False, verbose_name='Подписан на рассылку'),
        ),
    ]
