# Generated by Django 5.2.8 on 2025-12-01 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0005_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='datacenter.event', verbose_name='Мероприятие'),
        ),
    ]
