# Generated by Django 5.2.8 on 2025-12-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0006_alter_talk_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='is_active',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Активно?'),
        ),
    ]
